services:
  backend:
    build:
      context: .
    command: /bin/bash -c "sleep 10 && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434  # Permet au backend de trouver Ollama

 
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ~/.ollama:/root/.ollama  # Partage des modèles entre l'hôte et le container
    ports:
      - "11434:11434"
volumes:
  ollama-models:
